spring.application.name=conference
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.application.version=1.0.0

# management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.include=beans,metrics,info,health,loggers,readiness

spring.security.user.name=${SECURITY_USERNAME}
spring.security.user.password=${SECURITY_PASSWORD}

management.endpoint.health.show-details=always
